apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: juphc-tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: build-image
    - name: repo-url
    - name: branch
      default: main

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    - name: npminstall
      taskRef:
        name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - npminstall

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      runAfter:
        - tests